name: Deploy Ngx-Workshop Admin UI to DO Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Copy dist to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MFE_DROPLET_IP }}
          username: root
          key: ${{ secrets.MFE_SSH_PRIVATE_KEY }}
          source: 'dist/mfe-shell-admin/*'
          target: '/opt/mfe-shell-admin/'
          strip_components: 2

      - name: SSH and restart Nginx (optional, if needed)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MFE_DROPLET_IP }}
          username: root
          key: ${{ secrets.MFE_SSH_PRIVATE_KEY }}
          script: |
            # Optionally clear cache, reload nginx, etc.
            systemctl reload nginx || true
